# Generated by Django 4.1.2 on 2022-10-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nacimiento',
            new_name='fecha_creacion',
        ),
    ]
